CREATE TABLE IF NOT EXISTS `building` (
  `id` char(36) NOT NULL COMMENT 'consider uuid',
  `code` text DEFAULT NULL COMMENT '楼盘代码',
  `ukey` text DEFAULT NULL COMMENT '每个building唯一标示，必须与版本配合才能作为主键',
  `ver` text DEFAULT NULL COMMENT '版本',
  `keyword_tag` text DEFAULT NULL COMMENT '楼盘关键字',
  `description` text,
  `asset_id` text DEFAULT NULL COMMENT '资产id',
  `building_grade_id` text DEFAULT NULL COMMENT '楼盘等级id',
  `market_id` text DEFAULT NULL,
  `submarket_id` text DEFAULT NULL COMMENT '商圈id\n',
  `creator` text DEFAULT NULL,
  `owner` text DEFAULT NULL,
  `admin` text DEFAULT NULL COMMENT '资产管理员',
  `building_type` text DEFAULT NULL COMMENT '建筑类型',
  `building_name_cn` text DEFAULT NULL COMMENT '建筑中文名',
  `building_name_en` text DEFAULT NULL COMMENT '建筑英文名',
  `building_name_other` text DEFAULT NULL,
  `latitude` text DEFAULT NULL COMMENT '纬度',
  `longitude` text DEFAULT NULL COMMENT '经度',
  `address_cn` text DEFAULT NULL COMMENT '地址中文名',
  `vacancy_rate` text DEFAULT NULL COMMENT '住房率%',
  `building_area` text DEFAULT NULL COMMENT '建筑面积，total GFA',
  `rentable_area` text DEFAULT NULL COMMENT '可租用面积',
  `available_area` text DEFAULT NULL COMMENT '可用面积',
  `parking_ratio` text DEFAULT NULL COMMENT '车位密度\n4:1000',
  `parking_type` text DEFAULT NULL COMMENT '车位类型\n',
  `parking_rate` text DEFAULT NULL COMMENT '停车费',
  `parking_number` text DEFAULT NULL COMMENT '停车数',
  `parking_reserved_number` text DEFAULT NULL COMMENT '已预订停车位',
  `parking_area` text DEFAULT NULL COMMENT '停车面积',
  `building_clear_height` text DEFAULT NULL COMMENT '层高',
  `building_clear_height_net` text DEFAULT NULL COMMENT '净层高',
  `building_year` text DEFAULT NULL COMMENT '建筑年份',
  `building_completion_date` text DEFAULT NULL COMMENT '竣工时间',
  `building_sprinkler` text DEFAULT NULL COMMENT '灭火设施',
  `building_green_ratio` text DEFAULT NULL COMMENT '楼盘绿化率\n',
  `floor_count` text DEFAULT NULL COMMENT '总层数',
  `estimated_area` text DEFAULT NULL COMMENT '估计面积',
  `actual_area` text DEFAULT NULL COMMENT '实际面积',
  `min_floor_size` text DEFAULT NULL COMMENT '最小层面积',
  `max_floor_size` text DEFAULT NULL COMMENT '最大层面积',
  `typical_floor_area` text DEFAULT NULL COMMENT '整层面积',
  `lot_size` text DEFAULT NULL COMMENT '总占地面积',
  `building_ac_type` text DEFAULT NULL COMMENT '空调类型\ncentral\nindenpendent\nunknown',
  `building_ac_desc` text DEFAULT NULL COMMENT '空调描述',
  `freshness_date` text DEFAULT NULL COMMENT '建筑上市时间',
  `signage` text DEFAULT NULL,
  `tenancy` text DEFAULT NULL COMMENT '单租户或多租户\nsingle\nmultiple',
  `elevator_count` text DEFAULT NULL COMMENT '电梯数',
  `elevator_desc` text DEFAULT NULL COMMENT '电梯描述',
  `major_tenants` text COMMENT '主要租户',
  `phone` text DEFAULT NULL COMMENT '楼盘联系电话',
  `efficiency_rate` text DEFAULT NULL COMMENT '得房率',
  `handover_standard` text DEFAULT NULL COMMENT '交付标准',
  `floor_loading` text DEFAULT NULL COMMENT '楼板承重',
  `opex` text DEFAULT NULL,
  `current_opex_total` text DEFAULT NULL COMMENT '当年管理费',
  `opex_type` text DEFAULT NULL COMMENT '物业费类型',
  `img_name` text DEFAULT NULL COMMENT '用于传送文件名，无实际意义',
  `img_type` text DEFAULT NULL COMMENT '用于传送文件名，无实际意义',
  `gmt_create` text DEFAULT NULL,
  `gmt_modified` text DEFAULT NULL,
  `url_for_content` text DEFAULT NULL,
  `url_for_file` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `space` (
  `id` char(36) NOT NULL,
  `ukey` text DEFAULT NULL COMMENT '每个space唯一标示，必须与版本配合才能作为主键',
  `ver` text DEFAULT NULL COMMENT '版本(0表示最新版，其余顺序递增)',
  `asset_id` text DEFAULT NULL COMMENT '资产id，同一space的不同版本共享同一asset',
  `space_type_id` text DEFAULT NULL COMMENT '房源类型id',
  `building_id` char(36) DEFAULT NULL COMMENT '楼盘id，同一space的不同版本共享同一building',
  `contiguous_id` text DEFAULT NULL COMMENT '连续空间id',
  `creator` text DEFAULT NULL,
  `owner` text DEFAULT NULL,
  `admin` text DEFAULT NULL COMMENT '资产管理员',
  `floor` text DEFAULT NULL COMMENT '楼层',
  `unit` text DEFAULT NULL COMMENT '单元号',
  `min_divisible` text DEFAULT NULL COMMENT '最小分隔面积',
  `size` text DEFAULT NULL COMMENT '空间大小',
  `available_size` text DEFAULT NULL COMMENT '可用面积',
  `current_size` text DEFAULT NULL COMMENT '预测面积',
  `target_size` text DEFAULT NULL COMMENT '实测面积',
  `rate` text DEFAULT NULL COMMENT '每平米租金',
  `handover_standard` text DEFAULT NULL COMMENT '交付标准',
  `is_occupied` text DEFAULT NULL COMMENT '是否空置',
  `budget` text DEFAULT NULL COMMENT '租金预算',
  `is_contiguous` text DEFAULT NULL COMMENT '是否连续',
  `is_divisible` text DEFAULT NULL COMMENT '是否可分割',
  `LCD` text DEFAULT NULL COMMENT '合同起租日期',
  `LED` text DEFAULT NULL COMMENT '合同到期时间\nLease Term:（转租：自动确定＝LED-LCD; 非转租＝最大可租期限）',
  `date_vacant` text DEFAULT NULL COMMENT '租户离开日期',
  `date_available` text DEFAULT NULL COMMENT '房屋可用时间',
  `lease_type` text DEFAULT NULL COMMENT '是否转租\nlease\nsublease\nunknown',
  `space_clear_height` text DEFAULT NULL COMMENT '净层高',
  `name` text DEFAULT NULL COMMENT '房源标题',
  `opex` text DEFAULT NULL COMMENT '房源物业费',
  `sell_rate` text DEFAULT NULL COMMENT '出售价格',
  `shortest_lease_term` text DEFAULT NULL COMMENT '最短租期，按月',
  `longest_lease_term` text DEFAULT NULL COMMENT '最长租期，按月',
  `grace_lease_term` text DEFAULT NULL COMMENT '免租期',
  `management_status` text DEFAULT NULL COMMENT '状态，运营管理状态',
  `system_status` text DEFAULT NULL COMMENT '系统状态，枚举NORMAL, FROZEN, ON_MARKET, OFF_MARKET, ARCHIVED, REMOVED',
  `market_status` text DEFAULT NULL,
  `date_listed` text DEFAULT NULL COMMENT 'on_market时间',
  `description` text COMMENT '描述',
  `memo` text COMMENT '备忘',
  `gmt_create` text DEFAULT NULL,
  `gmt_modified` text DEFAULT NULL,
  `date_archived` text DEFAULT NULL,
  `url_for_content` text DEFAULT NULL,
  `url_for_file` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `building_operator` (
`id` char(36) NOT NULL,
`building_id` char(36) NULL DEFAULT NULL COMMENT 'building_id',
`company_id` char(36) NULL DEFAULT NULL COMMENT 'company_id',
PRIMARY KEY (`id`)
) COLLATE='utf8_general_ci' DEFAULT CHARSET=utf8;
DELETE FROM `building_operator`;


CREATE TABLE IF NOT EXISTS `company` (
`id` char(36) NOT NULL,
`name` text NULL DEFAULT NULL COMMENT '公司名',
`type` text NULL DEFAULT NULL COMMENT '公司类型\\n中介\\n开发商\\n租户\\n业主\\n物业公司\\n租赁代理',
`logo` text NULL DEFAULT NULL,
`website` text NULL DEFAULT NULL COMMENT '公司网址',
`telephone` text NULL DEFAULT NULL COMMENT '公司电话',
PRIMARY KEY (`id`)
) COLLATE='utf8_general_ci' DEFAULT CHARSET=utf8;
DELETE FROM `company` ;

 
CREATE TABLE IF NOT EXISTS `building_developer` (
`id` char(36) NOT NULL,
`building_id` char(36) NULL DEFAULT NULL COMMENT 'building_id\\n',
`company_id` char(36) NULL DEFAULT NULL COMMENT 'company_id\\n',
PRIMARY KEY (`id`)
) COLLATE='utf8_general_ci' DEFAULT CHARSET=utf8;
DELETE FROM `building_developer` ;
